import { Navbar } from "@/components/ui/navbar";
import Footer from "@/components/footer";
import { Montserrat } from 'next/font/google';
import "./globals.css";

export const metadata = {
  title: "Chihuahua IT Cluster",
  description: "Generated by create next app", 
};

const montserrat = Montserrat({
  subsets: ['latin'], 
  weights: ['400', '500', '600', '700'], 
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <head>
        <link rel="icon" href="/images/logos/citc/CITC_Logo.png" type="image/png" sizes="32x32" />
      </head>
      <body>
        <header>
          <Navbar />
        </header>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}