import Nav from "@/components/ui/navbar";
import Footer from "@/components/footer";
import { Montserrat } from 'next/font/google';
import "./globals.css";

export const metadata = {
  title: "Chihuahua IT Cluster",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ['latin'], 
  weights: ['400', '500', '600', '700'],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}